add_test([=[ext_finder.PYTHON]=]  /home/artjom/Desktop/Projects/linux_cmds/ls/build/test_ls [==[--gtest_filter=ext_finder.PYTHON]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ext_finder.PYTHON]=]  PROPERTIES WORKING_DIRECTORY /home/artjom/Desktop/Projects/linux_cmds/ls/cmake-build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ext_finder_.DIR]=]  /home/artjom/Desktop/Projects/linux_cmds/ls/build/test_ls [==[--gtest_filter=ext_finder_.DIR]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ext_finder_.DIR]=]  PROPERTIES WORKING_DIRECTORY /home/artjom/Desktop/Projects/linux_cmds/ls/cmake-build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ext_finder_.HIDDEN]=]  /home/artjom/Desktop/Projects/linux_cmds/ls/build/test_ls [==[--gtest_filter=ext_finder_.HIDDEN]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ext_finder_.HIDDEN]=]  PROPERTIES WORKING_DIRECTORY /home/artjom/Desktop/Projects/linux_cmds/ls/cmake-build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[dir_entry.FIRST]=]  /home/artjom/Desktop/Projects/linux_cmds/ls/build/test_ls [==[--gtest_filter=dir_entry.FIRST]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[dir_entry.FIRST]=]  PROPERTIES WORKING_DIRECTORY /home/artjom/Desktop/Projects/linux_cmds/ls/cmake-build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_ls_TESTS ext_finder.PYTHON ext_finder_.DIR ext_finder_.HIDDEN dir_entry.FIRST)
